Feature/target login page view
mwtz/target-web pull request #2
Opened 2022-04-13 17:28 UTC by mwtz

## Links:

[Ticket](https://trello.com/c/2ZmHuciN/15-3-as-a-user-i-should-be-able-to-login-so-i-can-use-my-target-mvd-account)

## What & Why:

Login page creation and styles for Target MVD account

features: 
* adding bootstrap
* change styles
* adding new text and image

## Notes:
Facebook signup and forgot password links don't have functionality yet

![image](https://user-images.githubusercontent.com/103122396/163236057-e1102439-c20e-4408-a8cd-bbc94ccb5f11.png)

## Risks, Mitigation & Rollback:

- [ ] Safe to Revert *check this box if this PR can be reverted without incident*

2022-04-13 17:51 UTC, dariokozicki approved these changes
🚀  Very good!

2022-04-13 18:07 UTC, juanfopaez requested changes
Good job martin!

2022-04-13 18:07 UTC, juanfopaez commented on src/components/form/Input/index.js
> +  <div className="d-flex flex-column text-center Input">
do you have any reason to in order to implement bootstrap instead of use flex box into your scss file directly ?

2022-04-13 18:07 UTC, juanfopaez commented on src/pages/Login/styles.scss
> +        line-height: 12.89px;
rem ?

2022-04-13 18:07 UTC, juanfopaez commented on src/pages/Login/styles.scss
> +          margin-bottom: rem(50px);
i would prefer if you use rem directly, this could help you https://nekocalc.com/px-to-rem-converter

2022-04-13 18:07 UTC, juanfopaez commented on src/pages/Signup/styles.scss
> +      line-height: 12.89px;
rem?

2022-04-13 18:07 UTC, juanfopaez commented on src/pages/Signup/styles.scss
> +      width: 180px;
same rem stuff for all px here :)

2022-04-13 18:07 UTC, juanfopaez commented on src/pages/Login/index.js
> +            <Button type="submit" disabled={isLoading}>
nice, love it

2022-04-13 19:30 UTC, mwtz commented on src/components/form/Input/index.js
> +  <div className="d-flex flex-column text-center Input">
Not quite, but the idea is to use the bootstrap utils

2022-04-13 19:31 UTC, mwtz commented on src/pages/Login/styles.scss
> +        line-height: 12.89px;
Its a function to define everything with rem [Here](https://medium.com/@bhargav3shah/scss-convert-pixel-values-to-rem-using-functions-f1cef575edfd)

2022-04-13 20:41 UTC, juanfopaez commented on src/pages/Login/styles.scss
> +      border-top: 0.5px solid $color-black;
one more rem here 🦈

2022-04-13 20:43 UTC, juanfopaez commented on src/components/form/Input/index.js
> +  <div className="d-flex flex-column text-center Input">
kk, probably the intention of this challenge is avoiding use of this kind of tools and implement css directly, but it is good to me :)

2022-04-18 18:56 UTC, juanfopaez approved these changes
Good Job sir!

2022-04-18 19:11 UTC, merged